//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Server.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Server.App_LocalResources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed server.
        /// </summary>
        public static string adv_1 {
            get {
                return ResourceManager.GetString("adv_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string adv_2 {
            get {
                return ResourceManager.GetString("adv_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Community.
        /// </summary>
        public static string adv_3 {
            get {
                return ResourceManager.GetString("adv_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted 24/7.
        /// </summary>
        public static string adv_4 {
            get {
                return ResourceManager.GetString("adv_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative mode is one of the main game modes in Minecraft. Creative mode strips away the survival aspects of Minecraft and allows players to easily create and destroy structures and mechanisms with the inclusion of an infinite use of blocks and flying. It also changes the background music. In Creative mode, players have no health or hunger bar to hamper their building (though it is still possible to eat, and the player&apos;s health still goes down if they take damage from the void). Creative mode allows players  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gamemode_crtv_content {
            get {
                return ResourceManager.GetString("gamemode_crtv_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore is a Java Edition exclusive variant of Survival. In this mode, the world is locked to Hard difficulty and the player cannot respawn after being killed. The key feature of Hardcore mode is that the player is not given the option to respawn upon death as they would in other game modes. Instead, there are two buttons on the death screen: &quot;Spectate world&quot; and &quot;Title screen.&quot; &quot;Spectate world&quot; sets the player to Spectator mode and respawns the player at the world&apos;s spawn point, making them able to view a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gamemode_hrdc_content {
            get {
                return ResourceManager.GetString("gamemode_hrdc_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore.
        /// </summary>
        public static string gamemode_hrdc_section {
            get {
                return ResourceManager.GetString("gamemode_hrdc_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available gamemode in our minecraft Server.
        /// </summary>
        public static string gamemode_Subtitle {
            get {
                return ResourceManager.GetString("gamemode_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival mode is one of the main game modes in Minecraft. Players must collect resources, build structures, battle mobs, eat, and explore the world in an effort to thrive and survive. In Bedrock Edition, players may receive achievements in a world not set to Flat while playing Survival Mode with cheats off, add-ons off, and host privileges off. If a player creates a world in creative mode and then loads it in Survival Mode, the player cannot earn achievements in that world. In Minecraft Survival, the main g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gamemode_surv_content {
            get {
                return ResourceManager.GetString("gamemode_surv_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamemode.
        /// </summary>
        public static string gamemode_Title {
            get {
                return ResourceManager.GetString("gamemode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure mode is a game mode intended for player-created maps, limiting some of the gameplay in Minecraft. In this mode, the player cannot directly destroy any blocks with any tools or place any blocks, in order to avoid spoiling adventure maps or griefing servers. Adventure mode is accessible only with commands or the game mode selector. Adventure mode is similar to Survival in that players receive damage from their environment, dying is possible, and players must manage hunger. However, it is different i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gamode_advn_content {
            get {
                return ResourceManager.GetString("gamode_advn_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string gamode_advn_section {
            get {
                return ResourceManager.GetString("gamode_advn_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative.
        /// </summary>
        public static string gamode_crtv_section {
            get {
                return ResourceManager.GetString("gamode_crtv_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival.
        /// </summary>
        public static string gamode_surv_section {
            get {
                return ResourceManager.GetString("gamode_surv_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Play!.
        /// </summary>
        public static string letsPlay {
            get {
                return ResourceManager.GetString("letsPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go here.
        /// </summary>
        public static string shop_link {
            get {
                return ResourceManager.GetString("shop_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upgrade/buy rank?.
        /// </summary>
        public static string shop_title {
            get {
                return ResourceManager.GetString("shop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Thank For.
        /// </summary>
        public static string thx_title {
            get {
                return ResourceManager.GetString("thx_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well...... Without me this minecraft never existed. Thank for your support.
        /// </summary>
        public static string thx1 {
            get {
                return ResourceManager.GetString("thx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks to the T-XIvIN Community for developing this site..
        /// </summary>
        public static string thx2 {
            get {
                return ResourceManager.GetString("thx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Minecraft Server Advantages.
        /// </summary>
        public static string title_ServerAdvantages {
            get {
                return ResourceManager.GetString("title_ServerAdvantages", resourceCulture);
            }
        }
    }
}
