//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Server.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal News() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Server.App_LocalResources.News", typeof(News).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btn_View {
            get {
                return ResourceManager.GetString("btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string btnReport {
            get {
                return ResourceManager.GetString("btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Publisher Profile.
        /// </summary>
        public static string btnViewProfile {
            get {
                return ResourceManager.GetString("btnViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        public static string nav_Anc {
            get {
                return ResourceManager.GetString("nav_Anc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a news.
        /// </summary>
        public static string nav_Create {
            get {
                return ResourceManager.GetString("nav_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From System.
        /// </summary>
        public static string nav_FromSys {
            get {
                return ResourceManager.GetString("nav_FromSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string nav_List {
            get {
                return ResourceManager.GetString("nav_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string nav_Rule {
            get {
                return ResourceManager.GetString("nav_Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random News.
        /// </summary>
        public static string Rndm_News {
            get {
                return ResourceManager.GetString("Rndm_News", resourceCulture);
            }
        }
    }
}
